development:
  adapter: postgresql
  encoding: unicode
  database: polisci_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: polisci_test
  pool: 5
  username:
  password:
